### ISSUE TITLE
Does this class only work with existing streams, or does it create a stream if it doesn't exist?

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/AWSKinesisStreams#9]
I think the answer is that it only works with existing streams, but just checking to make sure.

**Comment by mm-gmbd** [comment]
Also, same question for shards (and this is maybe more of a question about AWS Kinesis Data Streams) -- if I write to a stream and specify a non-existent shard, is it auto-created?

**Comment by mm-gmbd** [comment]
Per [the documentation](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_Operations.html), it appears that there are explicit methods for creating/deleting a stream, and I don't see those reflected in the class (at least, not yet :smile:).

As for shards, I don't see anything explicit about creating a shard, so it seems like that may happen automatically.

Can someone confirm? (Unfortunately, I don't have a way to stand up and instance quickly to determine the answer :/)

**Comment by betzrhodes** [comment]
@mm-gmbd - I'll take a look and get docs updated if they are incorrect

**Comment by betzrhodes** [comment]
This version of the library does not support creating streams or updating the number of shards a stream has. It appears both of these operations are listed in the AWS docs [create streams](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_CreateStream.html), and [update shard count](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_UpdateShardCount.html). I just skimmed through our README and found a note at the top about what operations the current library version supports: 

```
This version of the library supports the following functionality:

Writing data records into an Amazon Kinesis stream.
Getting data records from an Amazon Kinesis stream’s shard.
```

From what I can tell skimming through the AWS docs, the number of shards is a required parameter when a stream is created. This can be updated later with UpdateShardCount. The account may have limitations on the number of total shards that are allowed.

Hope this helps.
